version: '3'

services:
  postgres:
    image: postgres:16.0
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  redis:
    image: redis:7.2.3
    restart: on-failure
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

  auth_service:
    build: ./auth_service/src/
    restart: on-failure
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  nginx:
    image: nginx:1.25.3
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - auth_service
    ports:
      - "80:80"
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
